name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [24]

    steps:
      - uses: actions/checkout@v7

      - uses: pnpm/setup@v2
        with:
          runtime: node@${{ matrix.node }}
          cache: true

      - name: Format check
        run: pnpm run format

      - name: Run lint
        run: pnpm run lint && pnpm run test:lint-rules

      - name: Run typecheck
        run: pnpm run typecheck

      - name: Check l10n
        run: pnpm run l10n:check

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [24]

    steps:
      - uses: actions/checkout@v7

      - uses: pnpm/setup@v2
        with:
          runtime: node@${{ matrix.node }}
          cache: true

      - name: Run tests
        run: pnpm run test

      - name: Run extension tests
        run: xvfb-run -a pnpm run test:ext
